### PR TITLE
Query since & until using microtime

### PR DESCRIPTION
**Pull request by ht2**
Addresses issue in #766

### CODE REVIEW

**Comment by ryansmith94** [comment]
Not sure why there aren't two checks for this. Definitely should be.

**Comment by ht2** [comment]
@ryansmith94 OK, so this didn't run the conformance test - am I doing something dumb?

**Comment by ryansmith94** [comment]
I think Travis just didn't pick it up for some reason, if you can make another commit that might fix it.

**Comment by ht2** [comment]
Off we go :)

**Comment by ryansmith94** [comment]
Woo :+1: I think it was because I made a commit to develop just after you made this PR.

**Comment by ryansmith94** [comment]
Good stuff! :smile:

**Comment by ht2** [comment]
Awesome! OK, before I bring this into develop, I'm just going to have a snoop around for any other uses of MongoDate

**Comment by ryansmith94** [comment]
Ok mate sounds good.

**Comment by ht2** [comment]
Presuming this is an issue: https://github.com/LearningLocker/learninglocker/blob/issue/mongodate/app/locker/repository/Statement/EloquentLinker.php#L143

**Pull request merged**
