### PR TITLE
v1.11.0

### PR DESCRIPTION
**Pull request by daniel-abbey**
If you're upgrading from a version before 1.9.0 please review the [release notes for 1.9.0](https://github.com/LearningLocker/learninglocker/releases/tag/v1.9.0) before upgrading. Please see our [upgrading documentation](http://docs.learninglocker.net/upgrading/) for steps to be taken when upgrading.

### Minor Changes
1. Adds converts of user IDs to MongoIds. #737, #741, #743

### Patches
1. Fixes 'Verified' button styles on Admin Dashboard. #725
2. Fixes full agent search. #728
3. Fixes state API. #729
4. Adds more statement properties to autofill when editing exports. #731
5. Fixes invite when no role selected. #734
6. Adds links and translations to verification emails. #735
7. Fixes issue where LRS clients were not destroyed when the LRS was. #738
8. Updates error trace. #739
9. Adds URL type to Rackspace Fly System. #740

### CODE REVIEW

**Comment by ryansmith94** [comment]
#731 #735 #739 #740 are all minor changes @daniel-abbey :-)

**Comment by ht2** [comment]
Agree for the most part @ryansmith94 (apart from #739 which actually patches a problem we were seeing where not outputting to a string was throwing 500 memory errors on very particular calls!). @daniel-abbey, let's move #731,#735 & #740 into minor changes. My bad for not being for so particular!

**Comment by daniel-abbey** [comment]
Done.

**Comment by ryansmith94** [comment]
Ah right fair enough @ht2 with #739, I assume that's where the stack gets too large or something. No worries, sorry to be so particular, but I know how useful those notes have been in the past (to me anyway) so I want to make sure they're correct.

**Pull request merged**
