### PR TITLE
email improvements

### PR DESCRIPTION
**Pull request by pondermatic**
Improved emails by adding <a> tags to links, adding plain text versions and improving localization. The translations should be validated by Spanish and German speakers.

### CODE REVIEW

**Comment by daniel-abbey** [comment]
Hi @pondermatic, thanks for submitting this pull request. We will get back to you soon once we have tested the code.

**Comment by daniel-abbey** [comment]
Hi @pondermatic, this pull request has been approved and will be merged into our [1.10.1 milestone](https://github.com/LearningLocker/learninglocker/milestones/1.10.1). Many thanks for your efforts in discovering and fixing this bug.

**Comment by daniel-abbey** [comment]
Hi @pondermatic, I have discovered a bug in this code. Whe you invite a user from the Users section (no LRS selected), the first line of the email reads "user@example.com has invited you to join the 's Learning Locker Learning Record Store (LRS).". Please can this be fixed. Thanks

**Comment by pondermatic** [comment]
Hi @daniel-abbey, I am unable to reproduce the issue where the first line of the invite email contains `user@example.com`.

I did a search for that address in both the app code and vendor code and did not find it. I even searched for just `example.com` and did not find anything that would result in `user@example.com` used in the invite email.

The invite blade files use `$send->name`, which is set in `Locker\Helpers\User->inviteUser()` using `Auth::user()`.

**Comment by pondermatic** [comment]
Hi @daniel-abbey,
Perhaps I misunderstood your message. Is the problem with the invite email:
1) the email address, or 
2) that the empty title of the LRS is used, resulting in `has invited you to join the `**'s**` Learning Locker Learning Record Store (LRS).`?

If #2, then I agree that it is a bug. It was there before the changes I made. I will fix it though.

**Comment by pondermatic** [comment]
Because I don't speak German or Spanish, I used the Google translator for the "role" strings. If anyone speaks these languages, we would appreciate feedback.

The role help message does not seem to be accurate. My observer and plus users can not create LRSs.

**Comment by daniel-abbey** [comment]
This PR was merged into #747

**Pull request closed without merging**
