### PR TITLE
Adds interval and time graph to reports.

### PR DESCRIPTION
**Pull request by ryansmith94**
I would add it to the admin dashboard but it only works with the aggregation API at the moment (which is limited to LRSs).

### CODE REVIEW

**Comment by ryansmith94** [comment]
Not ready to merge due to failing Travis builds and because I want to add it to the LRS dashboards.

**Comment by ryansmith94** [comment]
Fixed tests and added graphs to LRS dashboards. To add to admin dashboard, a new route will need to be created for aggregation over all LRSs and the public/assets/js/libs/exp/src/AggregationRepo.ts file will need to be changed to allow for other aggregation routes.

**Comment by ryansmith94** [comment]
@daniel-abbey this needs to be demonstrated to James, Andrew, and Ben next Monday before merging, so it'll have to wait until the next release :+1: They may want to tweak some parts of it before it's merged.

**Comment by daniel-abbey** [comment]
Thanks Ryan

**Comment by ryansmith94** [comment]
No worries :-)

**Pull request closed without merging**
