### PR TITLE
Table formatting

### PR DESCRIPTION
**Pull request by hallshouse**
General table formatting.

I do not know where the layout files are for the Reporting and Exporting tables.
If you let me know, I'll be happy to adjust them to center TH text and TD icons as well as resize the column widths in some cases.

### CODE REVIEW

**Comment by ryansmith94** [comment]
Hi @hallshouse, thanks for the pull request. Please see my comment on the commit, once that change is made I'll be happy to merge this. The files you were looking for are linked below.

Reports
- https://github.com/LearningLocker/learninglocker/blob/develop/public/assets/js/reports/reports/table.html
- https://github.com/LearningLocker/learninglocker/blob/develop/public/assets/js/reports/reports/row.html

Exports
- https://github.com/LearningLocker/learninglocker/blob/develop/public/assets/js/exports/exports/collectionTemplate.html
- https://github.com/LearningLocker/learninglocker/blob/develop/public/assets/js/exports/exports/modelTemplate.html

**Comment by hallshouse** [comment]
Thanks @ryansmith94 I reverted the 2 column widths. Regarding the template files, I had made the changes in the reports and exports template HTML files in my pull request, however, this made no difference in my testing. The layouts did not change.

**Comment by ryansmith94** [comment]
Awesome. Yeah I was just about to say that it was a cache problem.

**Comment by ryansmith94** [comment]
I'll take a look at this PR this afternoon and get it merged.

**Comment by ryansmith94** [comment]
Looks good, thank you! :+1:

**Pull request merged**
