### PR TITLE
Allowed persona imports account ifi's to have the homepage set as a constant.

### PR DESCRIPTION
**Pull request by cbishopvelti**
Please remember to request a review from someone when this PR is ready for a code review.

#### Which issue does this close?
Closes LearningLocker/enterprise#964.

### CODE REVIEW

**Comment by ryansmith94** [comment]
Wait for https://github.com/LearningLocker/learninglocker/pull/1380 since that has been included in here.

**Comment by ht2** [comment]
This PR is blocked due to issue in #1380

**Comment by ryansmith94** [comment]
Probably best to find a way to remove the commits made in https://github.com/LearningLocker/learninglocker/pull/1380 from this PR Chris and then we can get this through QA separately.

**Comment by ryansmith94** [comment]
Replaced by https://github.com/LearningLocker/learninglocker/pull/1399 which removes blocking commits.

**Pull request closed without merging**
