### PR TITLE
Add a new line for next chunk.

### PR DESCRIPTION
**Pull request by kzkamiya**
When I tried csv exporting function of Learning Locker, a csv file of over 1000 rows did't include a newline in each 1000 rows.
So, I added a newline for next chunk.

### CODE REVIEW

**Comment by ryansmith94** [comment]
Hi thanks very much for the pull request. Hopefully I'll have time to give this a test next Tuesday when I'm back in the office.

**Comment by ryansmith94** [comment]
Just tested it, good spot and good fix, thanks a lot.

**Comment by kzkamiya** [comment]
Thank you!!

**Comment by ryansmith94** [comment]
You're welcome.

**Pull request merged**
