### PR TITLE
PHP 7.0 is not available

### PR DESCRIPTION
**Pull request by ysramirez**

### CODE REVIEW

**Comment by ryansmith94** [comment]
To test this, please change the [.travis.yml file](https://github.com/LearningLocker/learninglocker/blob/develop/.travis.yml) on line 4.

**Comment by ysramirez** [comment]
https://github.com/LearningLocker/learninglocker/issues/868

**Comment by PhillippOhlandt** [comment]
Just curious, why is php7 not supported?

**Comment by ht2** [comment]
@PhillippOhlandt, please read #893, #835 and #868,

**Comment by PhillippOhlandt** [comment]
@ht2 I read in another issue that v2 will be rewritten in NodeJS. Any ETA for that?

**Comment by ryansmith94** [comment]
Hey @PhillippOhlandt it will hopefully be some time in the second half of this year 👍

**Comment by PhillippOhlandt** [comment]
@ryansmith94 thanks for the info!

**Pull request merged**
