### PR TITLE
Fixed issue where an lrs's clients were not destroyed when the lrs was.

### PR DESCRIPTION
**Pull request by pondermatic**

### CODE REVIEW

**Comment by daniel-abbey** [comment]
Hi @pondermatic, thanks for submitting this pull request. We will get back to you soon once we have tested the code.

**Comment by daniel-abbey** [comment]
Hi @pondermatic, this pull request has been approved and will be merged into our [1.10.1 milestone](https://github.com/LearningLocker/learninglocker/milestones/1.10.1).

**Comment by pondermatic** [comment]
I found out that this fix is incomplete. oath_clients are left orphaned. Do not merge until I have fixed this.

**Comment by pondermatic** [comment]
This pull request now deletes related `client` and `oauth_clients` documents when an `lrs` is deleted.

**Comment by daniel-abbey** [comment]
This PR was merged into #747

**Pull request closed without merging**
