### PR TITLE
Set visibilityTimeout.

### PR DESCRIPTION
**Pull request by cbishopvelti**
Please remember to request a review from someone when this PR is ready for a code review.

#### Which issue does this close?
Closes https://github.com/LearningLocker/enterprise/issues/900.

### CODE REVIEW

**Comment by ryansmith94** [comment]
Assigning @ht2 to dev review because I have quite a limited understanding of SQS right now unfortunately whereas James understands it really well.

**Comment by ht2** [comment]
Think we're blocked on this due to SQS throwing its toys out the pram whenever the timeout changes on a queue.

Somewhat related to #900

Basically, instead of setting the visibilityTimeout on queue creation, we should update the attribute after creation to ensure we don't get collisions.

**Comment by ht2** [comment]
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html

**Comment by ht2** [comment]
Closing this, as @cbishopvelti says that this is now handled in #1397

**Pull request closed without merging**
