### PR TITLE
Change default value for pretend in mail config

### PR DESCRIPTION
**Pull request by sanduhrs**

### CODE REVIEW

**Comment by sanduhrs** [comment]
Fixes #594

**Comment by sanduhrs** [comment]
This fails because of #591

**Comment by ryansmith94** [comment]
Please could you merge in the develop branch. If the [suggestion I made previously today](https://github.com/LearningLocker/learninglocker/issues/581#issuecomment-95232074) is added to the code this will not be needed.

**Comment by ryansmith94** [comment]
Closing this because it's no longer an issue as of #598. Thanks for trying to help though @sanduhrs, really appreciate it! :+1:

**Pull request closed without merging**
