### PR TITLE
Foreign ids in lrs collection.

### PR DESCRIPTION
**Pull request by pondermatic**
Fixed issue #736. Converted foreign ids in lrs collection from string to MongoId values.

### CODE REVIEW

**Comment by daniel-abbey** [comment]
Hi @pondermatic, thanks for submitting this pull request. We will get back to you soon once we have tested the code.

**Comment by daniel-abbey** [comment]
Hi @pondermatic, this pull request has been approved and will be merged into our [1.10.1 milestone](https://github.com/LearningLocker/learninglocker/milestones/1.10.1).

**Comment by pondermatic** [comment]
The changes in this pull request are also in pull request #741.

**Comment by daniel-abbey** [comment]
#747

**Pull request closed without merging**
