### PR TITLE
Adds OAuth support.

### PR DESCRIPTION
**Pull request by ryansmith94**
Any credentials previously used for Basic Auth can now be used to request access tokens via OAuth. Please follow the steps below to use OAuth.

1. Request access token via `POST www.example.com/oauth/access_token` with `client_id` set to your key/username, `client_secret` set to your secret/password, and `grant_type` set to "client_credentials".
2. Receive `token` in response from step 1.
3. Make requests to the API by setting the `Authorization` header to "Bearer" followed by a space and the `token` you received in step 2.

**Notes**
The code inside the Helpers for this needs to be moved to the ClientRepository really. However, the LRS credentials need to be removed otherwise this code will be duplicated in the LrsRepository. We should remove the credentials from the Lrs model and just use credentials from the Client model.

### CODE REVIEW

**Comment by ht2** [comment]
@ryansmith94 Is this URL documented anywhere other than this PR?

**Comment by ryansmith94** [comment]
I don't think it is :-\ @ht2

**Comment by ht2** [comment]
No prob, its actually clearly used here: https://github.com/LearningLocker/learninglocker/blob/develop/app/tests/routes/OAuthTest.php

**Comment by ryansmith94** [comment]
Ah good spot :-)

**Comment by ProdEng** [comment]
This link seems to be no longer valid, where might an example now be located?

**Comment by ht2** [comment]
@ProdEng https://github.com/LearningLocker/learninglocker/blob/v1/app/tests/routes/OAuthTest.php

**Comment by ht2** [comment]
@ProdEng Please note that is V1 only

**Comment by ProdEng** [comment]
Thank you sir, any OAuth support within V2?

**Comment by andrewhickey** [comment]
Not yet, but it's on the roadmap

**Comment by ProdEng** [comment]
Ta, possible time frame for production release?

**Comment by ht2** [comment]
@ProdEng There are no timeframes. If you would like to contribute and start some work on that feature then contributions are always appreciated.

**Comment by ProdEng** [comment]
Love to, but not a developer just a lowly CIO/CTO.  Keep up the great work though as I am riding your horse to market.

Best,

Jon

**Comment by juangon** [comment]
Hi  @ryansmith94 , been trying to use /oauth2/token endpoint with client_id etc without luck. How these parameters should be sent? As JSON? As URL parameters? Thanks!

**Pull request merged**
